version: 2.1

orbs:
  build-tools: circleci/build-tools@3.0.0 # This is an orb. If you are not yet familiar with orbs, we will go over them soon. Orbs allow us to make our configs shorter by allowing us to "import" config in a similar way to a programming language's package manager.

jobs:
  build:
    docker: 
      - image: cimg/base:2022.10 
    resource_class: petez7519/runner929
    steps:
      - checkout
      - run: <command>
  test:
    docker:
      - image: cimg/<language>:<version TAG>
    steps:
      - checkout
      - run: <command>
workflows:
  build_and_test:
    jobs:
      - build
      - test