version: 2.1

orbs:
  # Add Orb here

jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.3
    steps:
      - checkout
      # Add step below to install Ruby version 2.6.3

      
      - run: ruby -v

workflows:
  run-jobs:
    jobs:
      - build

