version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:2022.10 
    parallelism: 2
    steps:
      - checkout
      # These two tests should run in parallel. Make it so!
      - run:
          name: Run Hello test
          command: |
            bash CircleCI-Training-Koans/src/test_hello.sh
      - run:
          name: Run Goodbye test
          command: |
            bash CircleCI-Training-Koans/src/test_goodbye.sh

workflows:
  test-workflow:
    jobs:
      - test

